### PR TITLE
Convert Snake Case names to Camel Case

### PR DESCRIPTION
**Pull request by HawaiianSpork**
This pull request automatically converts snake case names to camel case in addition to leaving the functionality that converts kebab case names to camel case.

### CODE REVIEW

**Comment by wcandillon** [comment]
@HawaiianSpork Looks good!

**Comment by wcandillon** [comment]
@HawaiianSpork Can you look into the failing tests?

**Comment by HawaiianSpork** [comment]
It looks like the unit test is assuming it can pass in snake case
parameters. So my pull request would be a breaking change for anyone who is
using snake case. Are you ok with that or should I add a configuration flag?

**Comment by wcandillon** [comment]
@HawaiianSpork I would be uncomfortable with a breaking change.

**Comment by wdawson4** [comment]
@HawiianSpork @wcandilon Please don't break snake case parameters

**Comment by HawaiianSpork** [comment]
@wdawson4 @wcandillon what do you think if we convert snake case parameters to camel case by default but have a flag for disabling it?  That way the codegen is consistent with how it handles kebab case and snake case but you can easily make it match the current behavior.

**Comment by wdawson4** [comment]
I'm okay with that, but I'm watching this convo. If I didn't read the convo or release notes, and the conversion was done, it would be tricky to diagnose what is wrong since its generated code.

Id say it would need a major version bump since its a breaking change.

I think the best way would be to not enable it by default, have a minor version change, and then enable it by default in a major version change.

**Comment by HawaiianSpork** [comment]
@wdawson4 & @wcandillon thanks for the advice.  I've updated the pull request accordingly.

**Comment by dciccale** [comment]
:+1:

**Comment by clubery** [comment]
Can you please at least document this? A real breaking change that caused me to wreck my brain. What was the reason behind this change?

**Pull request merged**
