### PR TITLE
Fix "empty" base path

### LINKED ISSUE #117: Single slash base path
If the base path is only a single slash the generation is not working properly.
It adds two slashes to the url (http://myapp.com//something).

### PR DESCRIPTION
**Pull request by chdanielmueller**
closes #117

### CODE REVIEW

**Comment by wcandillon** [comment]
@chdanielmueller thks for this PR! Can you give me a sample swagger file I can use for reproducing the issue and for testing?

**Comment by chdanielmueller** [comment]
Hi @wcandillon,

This example json should reproduce the error.
The problem is the basePath parameter.

```json
{
  "info": {
    "title": "Hello World",
    "version": "1.0.0",
    "description": "A sample API"
  },
  "host": "localhost:3000",
  "basePath": "/",
  "swagger": "2.0",
  "paths": {
    "/hello": {
      "get": {
        "description": "Returns the homepage",
        "responses": {
          "200": {
            "description": "hello world"
          }
        }
      }
    }
  }
}
```

**Comment by wcandillon** [comment]
@chdanielmueller Thank you so much for pointing out this issue. Shouldn't `basePath` be normalized to have its trailing slash remove instead? While your PR seems to be fix `"basePath": "/",`, it doesn't seem to work for `"basePath": "/v1/",` for instance?

**Comment by chdanielmueller** [comment]
You are right...
I changed the code to use a regex which removes trailing slashes.

**Pull request merged**
