### PR TITLE
Make lint and beautify optional

### PR DESCRIPTION
**Pull request by ruhley**
If lint or beautify are passed into the options as false than it will not run it. If beautify is not run then it will run our custom beautify which just removes lots of newlines.

### CODE REVIEW

**Comment by wcandillon** [comment]
@ruhley I don't think it make sense since the generated file will go through some building steps (concat, uglify).  I'm not sure about your use case. Can you remove the `beauty()` function?

**Comment by ruhley** [comment]
I am creating lots of libraries for my api, so that people who use it can download a file and use it on their website. And for some reason, I sometimes get errors from lint or beautify so I would just like to not do them. Of course they run by default so most people won't know.

I have removed the ```beautfy()``` function and added an ```after``` option. If a function is passed in, it will run it after everything else.

**Comment by wcandillon** [comment]
@ruhley The after option doesn't appear useful, why not process the result outside this function? Regarding the linting issue, you are getting, could you elaborate? Disabling the linting can be very dangerous and I would rather understand why these linting error arise in the first place.

**Comment by wcandillon** [comment]
@ruhley I'm closing this at the moment. I am not convinced yet by the use case. But I am still open to discuss things.

**Pull request closed without merging**
