### PR TITLE
Merge ts branch into master.

### PR DESCRIPTION
**Pull request by alexkrauss**
... and release to npm, since this is really useful. :-)

### CODE REVIEW

**Comment by laurensvanpoucke** [comment]
when will this pull request be released to npm? :)

**Comment by wcandillon** [comment]
@alexkrauss Is is possible to clean up the template folder by making filenames more explicits? For instance `node-typedef.mustache` doesn't sound like a good name. In the test you added, can you check if the generated file is typescript valid? using tslint for instance?

**Comment by alexkrauss** [comment]
@wcandillon What names would you suggest then?

In the test, the result is already checked against a predefined expectation, so I'm not sure, adding a tslint check adds anything except overhead. I was thinking of this more as a unit test, with a predefined input and output... One could also think about proper integration testing, but then we would also have to make sure that the generated type definitions match the generated code... This is certainly more work.

**Comment by wcandillon** [comment]
@alexkrauss Thank you so much for doing this. I have made a branch that superseeds this. I reused the typeconvertion function you wrote.

**Pull request closed without merging**
