### PR TITLE
Add single quotation mark into default value

### PR DESCRIPTION
**Pull request by zuhito**
I found a bug when I used the following swagger definition of Microsoft Cognitive Services.

https://westus.dev.cognitive.microsoft.com/docs/services/56f91f2d778daf23d8ec6739/export?DocumentFormat=Swagger&ApiName=Computer%20Vision%20API%20-%20v1.0

I think that single quotation mark is needed in the default value of parameter.
Could you check my code and solve it?

### CODE REVIEW

**Comment by zuhito** [comment]
Could you check the code? It's simple bug.

**Comment by ChrisJamesC** [comment]
What if the default value is not a string ?

**Comment by zuhito** [comment]
I think that the value is always string. If swagger specification accepts number as the value, I'll add handling to convert string to "string".

**Comment by wcandillon** [comment]
@zuhito I'm strongly recommend that you move away from this package in favor of another one, see: https://github.com/wcandillon/swagger-js-codegen#we-are-looking-for-a-new-maintainer

**Comment by zuhito** [comment]
@wcandillon Thank you for your comment. I understand your situation and try to fork this project.
By the way, Can I become the maintainer of the project? I'm using this module in production. Therefore, I can use my time to contribute this project.

**Pull request closed without merging**
