### PR TITLE
Fix build error in generated TypeScript files + add optional logger

### PR DESCRIPTION
**Pull request by Hacklone**
- Added optional Logger to TypeScript
- Fixed TypeScript build error

### CODE REVIEW

**Comment by Hacklone** [comment]
Is there any progress with this?

**Comment by wcandillon** [comment]
@Hacklone: I don't see any circleci results for this PR, do you know why?

**Comment by Hacklone** [comment]
Absolutely no idea :) Can it be triggered manually?

**Comment by Hacklone** [comment]
So what should we do? :)

**Comment by Hacklone** [comment]
Hey, any progress with this PR?

**Comment by Hacklone** [comment]
...

**Pull request merged**
