### PR TITLE
Fix issues with TypeScript code generation

### PR DESCRIPTION
**Pull request by adufilie**
Add support for enums and type declarations, fix TS errors when using strictNullChecks and noImplicitAny

### CODE REVIEW

**Comment by wcandillon** [comment]
@adufilie this is great! Can you provide an example that generates these enums and I will add it to the test suite and merge this.

**Comment by adufilie** [comment]
Example swagger json: http://pastebin.com/raw/eiC5yayi

**Comment by adufilie** [comment]
I think this fixes #115 / #139

**Comment by wcandillon** [comment]
@adufilie thks a lot!

**Pull request merged**
